### PR TITLE
Connected Components Labeling

### PR DESCRIPTION
**Pull request by RossBrunton**
Sorry this took so long. It's a lot of code, and it's hard to see where one part failing breaks everything else. But I managed it in the end.

It's probably not optimal at all, and uses up tons of memory. Maybe I can improve it later, or someone has suggestions to improve it. But it's a good initial implementation at the very least, probably.

### CODE REVIEW

**Comment by robstewart57** [comment]
Hi @RossBrunton I've just forked your repo and checked out your `connected` branch. I was able to run this code, and I think it worked. I.e. the either 2 or 3 three different shades of colour, excluding black. Excellent stuff!

I do get quite a few:

    Err: Too many classes in Reduce

Is that anything untoward?

What determines the number of connected components, or different shades of gray in this case? I see 2 or 3. Is it determined by the input image, or is this hard coded somewhere in your implementation?

**Comment by robstewart57** [comment]
@RossBrunton Also, is there an example YUV image for which this implementation works particularly well?

**Comment by RossBrunton** [comment]
That error message means that there are more than 255 classes (connected segments), which can't be represented in a 8 bit image (instead, extra ones are coloured black). And there are up to 255 classes, each of which is given a shade of gray in the output image.

**Comment by RossBrunton** [comment]
https://github.com/RossBrunton/orc-samples/tree/master/512_bw I've created a repository for test images.

The image that shows clearly how the algorithm works, I think, is:
islands

While a more interesting one is:
lena

**Comment by robstewart57** [comment]
@RossBrunton I am able to reproduce the output for Lena, that you show above.

Some feedback on the pull request. Would it be possible to refactor this, such that connected_components.xdf reads from an "in1" port and writes to an "out1" port, rather than the `FileReader` and `EndOfStream` actors directly. This is partly to do with de-coupling the algorithm from the IO actors, but also because the FPGA backend of Orcc that we use cannot handle native CPU actors (the file reader and writer actors use native runtime calls to C for reading/writing bytes to disk). The backend requires inputs and outputs to be specified at Orcc ports. One the the IO networks in `image.xdf.io` could be used to test your implementation again.

It'd be really interesting to see the effect of your connected components implementation on videos, rather than just images. Here is a 15 frame YUV video of a squirrel you might want to try:

http://samples.mplayerhq.hu/raw-video/squirrel-720x576-444P.yuv

$ ffplay -pixel_format yuv444p -video_size 720x576 squirrel-720x576-444P.yuv

It might need some hackery in the constants.cal file, a well as setting up an IO actor pipeline to convert the yuv444p into a single colour channel Y to feed your implementation graph.

**Comment by RossBrunton** [comment]
I tried using it with a video, but it seems to have hung somewhere.

As for the refactoring, I didn't even realise that was a thing that I could do! Unfortunately, that seems to cause the code to hang as well.

I'll look at these two things in the next few days.

**Comment by robstewart57** [comment]
@RossBrunton you've discovered the main drawback of *dynamic* (rather than *static*) datafow programming, it can be difficult to debug deadlocks. It'll be interesting to know how you get on. And if you can figure out how to make it work with a video, that'd be very cool.

What's the answer to:

> What determines the number of connected components, or different shades of gray in this case? I see 2 or 3. Is it determined by the input image, or is this hard coded somewhere in your implementation?

**Comment by RossBrunton** [comment]
The algorithm I'm using is described here http://homepages.inf.ed.ac.uk/rbf/HIPR2/label.htm

We don't decide the number of connected components ahead of time, the algorithm roughly works like this:

* Find all the pixels that are "touching", and use this to divide the image into classes.
* Join together all the classes that are touching 
* (Optionally) convert the values of these classes such that they are all under 256.

We don't set out to try to get two or three connected components, instead we set out to find which components exist.

**Comment by robstewart57** [comment]
> We don't set out to try to get two or three connected components, instead we set out to find which components exist.

That's better than hard coding the number of number of component shades, because it is more general to suite all possible visual environments, so that's good.

**Comment by RossBrunton** [comment]
Okay, so move the codebase to a new computer (with a new, empty build directory), doesn't work. Put in a println statement into an actor to check how far through it is, and it starts working. Remove said println statement, and it still works. Nuke build directory and recreate it from scratch, and it still works.

So yeah, it suddenly started working when using the connected_component actor (not for videos yet), and I'm not sure why. I'm going to chalk it down to Eclipse being weird.

**Comment by robstewart57** [comment]
@RossBrunton I feel your pain. One thing you can try when this happens. In eclipse: Project -> Clean . I know from past experience that changes to constants declared in unit modules are propagated to actor source code unless the project is cleaned before compilation. The cause: Orcc tries to improve performance efficiency of the IDE by caching actor and network files in the `bin/` directory, as files  ending `.ir`.

Also, for debugging, compile with very large FIFOs in compilation options, e.g. 2^16 = 131072 .

**Comment by robstewart57** [comment]
@RossBrunton has `ImageProcessing/src/image/xdf/io/connected_components.png` been committed and pushed accidentally? There's no need for screenshots in this repo.

**Comment by RossBrunton** [comment]
That screenshot is used in the documentation, I figured it would be useful for the docs to contain a diagram of the layout of the actor.

**Comment by RossBrunton** [comment]
And I got video working, turns out I just forgot to increment a counter.

**Comment by robstewart57** [comment]
@RossBrunton video works? cool! Out of curiosity, would you be able to put the outputted YUV file somewhere, maybe your ~/www/ so that I could take a look using ffplay?

**Comment by RossBrunton** [comment]
I've attached it in a zip file. I also decreased the threshold value so the squirell is actually detected.

[out.yuv.zip](https://github.com/robstewart57/orc-apps/files/788066/out.yuv.zip)

**Comment by robstewart57** [comment]
Very cool indeed.

If only we had a longer video to show it working in a slightly more animated scene with lots of activity going on. A sports scene, or drone footage, or what not. I think I spotted that you had scripts for file conversion in one of your repositories that you linked to, though without looking the the man pages for ffmpeg, I wouldn't know how to convert an, e.g. 300 frame video into a YUV file (which would be 10 seconds of footage at 30 FPS, to state the painfully obvious).

**Comment by robstewart57** [comment]
> That screenshot is used in the documentation, I figured it would be useful for the docs to contain a diagram of the layout of the actor.

I think the Orcc community would prefer that this orc-apps repository remains lean, i.e. just version controllable source files. Could there be a text description of that graph instead? If you are happy with this, i.e. to remove the image file binary from this pull request, it'd need to be fully purged from the history, i.e. that the binary blob for this file does not appear anywhere in the git repository history.

**Comment by robstewart57** [comment]
@RossBrunton it's also dawned on me that you may be able to actually run this with a camera, if your computer has a webcam. A few years back I added to the Orcc runtime the ability to use a native actor that reads from image streams from a camera via an OpenCV binding, rather than the `FileReader` actor for reading from a YUV file.

The runtime commit:
https://github.com/orcc/orcc/commit/fa5d6d4fc6017efc32deede243460dfcedb9eea0

In the orc-apps repository there is a `CameraStreaming` directory, here's the commit:
https://github.com/orcc/orc-apps/commit/b65ad2bb20cb279ca642ad488673c9c374963f99

It gives you a YUV stream just like the `FileReader` actor does.

In there is a `TopCameraStreaming.xdf` to test things out. If you add this `CameraStreaming` project as a dependency to the `ImageProcessing` project (just for testing your algorithm, rather than committing this as a dependency in the repo), then you might be able to use `CameraStreaming/src/std/io/SourceCamera.cal` to run connected components on your webcam feed.

Note you'll also need to add the `System` project as a dependency to `ImageProcessing` too, so that `System/src/std/stdio/SourceCamera.cal` is available.

**Comment by robstewart57** [comment]
@RossBrunton can this PR be merged?

**Comment by RossBrunton** [comment]
I'm still waiting for the rest of my group to read over it, but I think we're all to focused on the HOG stuff.

I'll remove the image file when I get back home later, and then I'll let you merge it.

**Comment by robstewart57** [comment]
> I'll remove the image file when I get back home later, and then I'll let you merge it.

OK cool.

**Comment by robstewart57** [comment]
Hi @RossBrunton Can I squash and merge this PR now?

**Comment by RossBrunton** [comment]
Should be fine, just give it a proof read and make sure I'm not doing anything majorly wrong.

**Comment by robstewart57** [comment]
Squashed and merged, thanks!

**Pull request merged**
