### PR TITLE
(ImageProcessing) Adds image.arithmetic.subtraction function

### PR DESCRIPTION
**Pull request by cajturner**
This function takes 2 inputs. Gin1 the original image stream and Gin2 the constant or image stream. Each token in Gin1 is then subtracted from Gin2 and sent to Gout. If the addition is less than 0, 0 is returned.

@RossBrunton @Teymoor-Ali @VincentDawn @robstewart57 @KirstyRD Could someone please review.

### CODE REVIEW

**Comment by robstewart57** [comment]
Looks good, thanks.

**Comment by Teymoor-Ali** [comment]
Cool, subtraction looks good.

**Comment by RossBrunton** [comment]
Uh, wouldn't `(x - y) > 0` always be true because it's unsigned?

**Comment by robstewart57** [comment]
@RossBrunton good question. The semantics of CAL arithmetic operations are unclear, or at least how the Orcc compiler treats unsigned integers. Perhaps a small experiment and report back? For both signed and unsigned integers, and also values beyond their bitwidth ranges. Something like, in an action:

```
var uint(size=8) a = 2,
      uint(size=8) b = 3,
      uint(size=8) c = 257,
      uint(size=8) d = 4
do
  println("a - b : " + (a - b));
  println("a > b : " + (a > b));
  println("c : " + c);
  println("c + d : " + (c + d));
  println("c - d : " + (c - d);
```

Given that when compiling to C, you're inheriting the semantics of how C deals with 8, 16, 32.. signed/unsigned integers (although strictly speaking, CALs semantics should be entirely independent of the semantics of any language which CAL compiles to as a backend). I don't think the Orcc gives any sanitising treatment to integers. What does this print?

At some point as you get onto the medium and higher level algorithms, you'll come to realise that not all algorithms are expressible with unsigned 8bit 0-255 pixel values. Let's discuss that when we come to it.

**Pull request merged**
